### ISSUE TITLE
When 100% zoomed out the map shifts left and its no longer centered on the assigned coordinates.

### ISSUE THREAD

**Issue by StefanJoh** [Dataforsyningen/okapi#38]
This happens regardless if the map is in maximized mode or not.

**Comment by Gebuz** [comment]
Hi StefanJoh,
Thanks for the feedback. The shift when zooming out is intentional, it's there to restrict the view to the extent of the map, as to not show a lot of white space in one direction when it could be showing more of the map in the opposite direction. If there is a specific use case where this is causing issues I can add a parameter to set the extent manually instead.

**Comment by StefanJoh** [comment]
Hi, yes a behavior where it by default acts as today and an opt in parameter for setting the extent manually to be able to control the left shift would be useful for us. Have you also had time to look in to the issue with the slider not dynamically fitting inside the height of the containing map?

**Comment by Gebuz** [comment]
Yes, we're looking into adding that aswell.

**Comment by Gebuz** [comment]
added in v1.4
